baseURL = 'https://technologies-of-history.github.io/'
languageCode = 'en-us'
title = 'Technologies of History'
theme = "hugo-book"
enableGitInfo = true
[params]
	BookTheme = 'auto'
	BookTOC = true
	BookSection = 'docs'
	BookLogo = 'cuneiform.png'
	BookRepo = 'https://github.com/technologies-of-history/fall-2025'
	BookCommit = 'commit'
	BookDateFormat = 'Jan 2, 2006'
	BookSearch = true
	author = "Melissa Reynolds"